name: detect-secrets
on: [pull_request]
jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: detect-secrets
      uses: karankohli13/action-detect-secret@master
      with:
        slack_token: ${{ secrets.slack_token }}
        baseline: "./.secrets.baseline"
        reporter: github-pr-review