name: detect-secrets
on: [pull_request]
jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Current Job Log URL
      id: jobs
      uses: Tiryoh/gha-jobid-action@v0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        job_name: detect-secrets
    - name: detect-secrets
      uses: karankohli13/action-detect-secret@master
      with:
        slack_token: ${{ secrets.slack_token }}
        baseline_file: "./.secrets.baseline"
        job_url: ${{ steps.jobs.outputs.html_url }}"